# Generated by Django 2.0.3 on 2018-03-14 20:47

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('nsr_id', models.CharField(max_length=120, null=True)),
                ('vrf', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pe_ip', models.CharField(blank=True, max_length=120, null=True)),
                ('ce_ip', models.CharField(blank=True, max_length=120, null=True)),
                ('mask', models.CharField(blank=True, max_length=120, null=True)),
                ('rp', models.CharField(blank=True, max_length=120, null=True)),
                ('speed', models.CharField(blank=True, max_length=120, null=True)),
                ('interface', models.CharField(blank=True, max_length=120, null=True)),
                ('profile', models.CharField(blank=True, max_length=120, null=True)),
                ('encap', models.CharField(blank=True, max_length=120, null=True)),
                ('encapID', models.CharField(blank=True, max_length=120, null=True)),
                ('vrf', models.CharField(blank=True, max_length=120, null=True)),
                ('client_as', models.CharField(blank=True, max_length=120, null=True)),
                ('telmex_as', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Hostname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('local_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), size=None)),
                ('os', models.CharField(choices=[('ios', 'IOS'), ('xr', 'IOS XR'), ('junos', 'Junos OS')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuitID', models.CharField(blank=True, max_length=120, null=True)),
                ('channelID', models.CharField(blank=True, max_length=120, null=True)),
                ('pgla', models.IntegerField(blank=True, null=True)),
                ('nsr', models.CharField(blank=True, max_length=120, null=True)),
                ('site_name', models.CharField(blank=True, max_length=120, null=True)),
                ('client_segment', models.CharField(max_length=120, null=True)),
                ('pm', models.CharField(blank=True, max_length=120, null=True)),
                ('imp', models.CharField(blank=True, max_length=120, null=True)),
                ('ise', models.CharField(blank=True, max_length=120, null=True)),
                ('capl', models.CharField(blank=True, max_length=120, null=True)),
                ('service', models.CharField(blank=True, max_length=120, null=True)),
                ('movement', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(blank=True, max_length=120, null=True)),
                ('local_id', models.CharField(blank=True, max_length=120, null=True)),
                ('interface', models.CharField(blank=True, max_length=120, null=True)),
                ('profile', models.CharField(blank=True, max_length=120, null=True)),
                ('speed', models.CharField(blank=True, max_length=120, null=True)),
                ('state', models.CharField(blank=True, max_length=120, null=True)),
                ('motive', models.CharField(max_length=120, null=True)),
                ('on_hold', models.CharField(blank=True, max_length=120, null=True)),
                ('duedate_acc', models.CharField(max_length=120, null=True)),
                ('entraga_ciap', models.CharField(max_length=120, null=True)),
                ('reception_ciap', models.DateField(blank=True, null=True)),
                ('billing_date', models.DateField(blank=True, null=True)),
                ('duedate_ciap', models.DateField(blank=True, null=True)),
                ('activation_date', models.DateField(blank=True, null=True)),
                ('cnr', models.CharField(max_length=120, null=True)),
                ('ddr', models.CharField(max_length=120, null=True)),
                ('daf', models.CharField(max_length=120, null=True)),
                ('duration', models.CharField(max_length=120, null=True)),
                ('duration_contract', models.CharField(max_length=120, null=True)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgla.Client')),
            ],
        ),
        migrations.CreateModel(
            name='LookingGlass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('path', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('protocol', models.CharField(choices=[('ssh', 'SSH'), ('telnet', 'TELNET'), ('url', 'URL')], max_length=120)),
                ('port', models.IntegerField(default=80)),
                ('extra', models.CharField(max_length=120)),
                ('nextlevel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pgla.LookingGlass')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120)),
                ('created', models.DateField()),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgla.Link')),
            ],
        ),
        migrations.CreateModel(
            name='Participan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('company', models.CharField(max_length=120, null=True)),
                ('number', models.CharField(max_length=120, null=True)),
                ('email', models.CharField(max_length=120, null=True)),
                ('position', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=120)),
                ('opener', models.CharField(max_length=120)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgla.Link')),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='participants',
            field=models.ManyToManyField(to='pgla.Participan'),
        ),
        migrations.AddField(
            model_name='link',
            name='relatedLink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pgla.Link'),
        ),
        migrations.AddField(
            model_name='country',
            name='lg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgla.LookingGlass'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='hostname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgla.Hostname'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pgla.Link'),
        ),
    ]
