# Generated by Django 2.0.3 on 2018-03-14 21:09

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgla', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='nsr_id',
        ),
        migrations.AddField(
            model_name='client',
            name='routes',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='vrf',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), blank=True, null=True, size=None),
        ),
    ]
