# Generated by Django 2.0.3 on 2018-03-15 14:20

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgla', '0003_auto_20180314_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lookingglass',
            name='nextlevel',
        ),
        migrations.AlterField(
            model_name='lookingglass',
            name='extra',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
