# Generated by Django 2.0.3 on 2018-03-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgla', '0004_auto_20180315_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lookingglass',
            old_name='extra',
            new_name='extras',
        ),
    ]
