# Generated by Django 2.0.3 on 2018-03-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgla', '0006_auto_20180319_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='channelID',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='on_hold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='site_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
