# Generated by Django 2.0.3 on 2018-03-20 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgla', '0007_auto_20180319_1617'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participan',
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='number',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
