# Generated by Django 2.0.3 on 2018-03-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgla', '0008_auto_20180320_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userID',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
