# Generated by Django 2.0.3 on 2018-03-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgla', '0009_auto_20180320_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='duedate_acc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='entraga_ciap',
            field=models.DateField(blank=True, null=True),
        ),
    ]
