# Generated by Django 2.0.3 on 2018-03-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgla', '0010_auto_20180320_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='on_hold',
        ),
        migrations.AlterField(
            model_name='link',
            name='channelID',
            field=models.CharField(blank=True, editable=False, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='circuitID',
            field=models.CharField(blank=True, editable=False, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='cnr',
            field=models.IntegerField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='state',
            field=models.CharField(blank=True, choices=[('INSTALACION SUSPENDIDA', 'INSTALACION SUSPENDIDA'), ('ACCESO SOLICITADO (ACSO)', 'ACCESO SOLICITADO (ACSO)'), ('ACCESO LISTO (ACLI)', 'ACCESO LISTO (ACLI)')], max_length=120, null=True),
        ),
    ]
