# Generated by Django 2.0.3 on 2018-03-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgla', '0011_auto_20180321_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisionTime',
            fields=[
            ],
            options={
                'verbose_name': 'Provisioning Time',
                'verbose_name_plural': 'Provisioning Times',
                'proxy': True,
                'indexes': [],
            },
            bases=('pgla.link',),
        ),
        migrations.RenameField(
            model_name='link',
            old_name='channelID',
            new_name='channel_id',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='circuitID',
            new_name='circuit_id',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='userID',
            new_name='slack_id',
        ),
        migrations.AlterField(
            model_name='link',
            name='client_segment',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='cnr',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
