# Generated by Django 2.0.3 on 2018-03-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgla', '0012_auto_20180322_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='cnr',
            field=models.IntegerField(max_length=120, null=True),
        ),
    ]
