# Generated by Django 2.0.3 on 2018-03-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgla', '0013_auto_20180322_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='cnr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
