# Generated by Django 2.0.3 on 2018-04-02 16:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgla', '0014_auto_20180322_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='ce_ip',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='CE IP'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='encap',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Encapsulation'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='encapID',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Encapsulation ID'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='pe_ip',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='PE IP'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='rp',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='RP'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='vrf',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='VRF'),
        ),
        migrations.AlterField(
            model_name='hostname',
            name='local_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), blank=True, null=True, size=None),
        ),
    ]
