# Generated by Django 2.0.3 on 2018-04-02 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgla', '0015_auto_20180402_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='cnr',
            field=models.IntegerField(blank=True, null=True, verbose_name='CNR'),
        ),
        migrations.AlterField(
            model_name='link',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgla.Country'),
        ),
        migrations.AlterField(
            model_name='link',
            name='local_id',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Local-ID'),
        ),
    ]
