# Generated by Django 2.0.3 on 2018-04-02 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgla', '0017_auto_20180402_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='country',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pgla.Country'),
            preserve_default=False,
        ),
    ]
