# Generated by Django 2.0.3 on 2018-04-03 14:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgla', '0018_auto_20180402_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='vrf',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), default=[], size=None),
        ),
    ]
