# Generated by Django 2.0.3 on 2018-04-03 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgla', '0019_auto_20180403_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='pgla.Link'),
        ),
    ]
